# Generated by Django 3.0.3 on 2021-09-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('sku', models.CharField(blank=True, max_length=40, null=True)),
                ('image_link', models.ImageField(blank=True, null=True, upload_to='static/uploaded_images')),
                ('name', models.CharField(max_length=500, null=True)),
                ('sizes', models.CharField(max_length=500, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
